set(_CATKIN_CURRENT_PACKAGE "main_pkg")
set(main_pkg_VERSION "0.0.0")
set(main_pkg_MAINTAINER "Adel Dennaoui <adel.dennaoui@alten.it>")
set(main_pkg_PACKAGE_FORMAT "2")
set(main_pkg_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "std_srvs" "xacro" "rviz")
set(main_pkg_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "sensor_msgs" "std_srvs" "xacro" "gazebo_msgs" "xacro" "rviz")
set(main_pkg_BUILDTOOL_DEPENDS "catkin")
set(main_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(main_pkg_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "sensor_msgs" "std_srvs" "xacro" "gazebo_msgs" "xacro" "rviz")
set(main_pkg_RUN_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "sensor_msgs" "std_srvs" "xacro" "gazebo_msgs" "rviz")
set(main_pkg_TEST_DEPENDS )
set(main_pkg_DOC_DEPENDS )
set(main_pkg_URL_WEBSITE "")
set(main_pkg_URL_BUGTRACKER "")
set(main_pkg_URL_REPOSITORY "")
set(main_pkg_DEPRECATED "")